# Generated by Django 4.1 on 2022-09-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=50)),
                ('Size', models.IntegerField()),
                ('Colour', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
